from django.urls import path
from .views import (
    get_all_docs,
    doctor_detail,
    get_all_bookings,
    booking_detail,
    reschedual_booking,
    complete_booking,
    doctor_patients,
    get_patient_plan,
    create_patient_plan,
    create_patient_medicine,
    get_patient_medicine,
    get_doctor_reviews,
    doctor_comment,
    list_doctor_comments,
    add_question,
    create_test,
    list_patient_tests,
    list_patient_question,
    create_prescription,
    list_prescriptions,
)

urlpatterns = [
    path("", get_all_docs, name="doctor-list"),
    path("<int:pk>/", doctor_detail, name="doctor"),
    path("bookings/", get_all_bookings, name="booking"),
    path("reviews/", get_doctor_reviews, name="reviews"),
    path("bookings/<int:pk>/reschedual/", reschedual_booking, name="reschedual-doctor"),
    path("bookings/<int:pk>/complete/", complete_booking, name="reschedual-doctor"),
    path("bookings/<int:pk>/", booking_detail, name="booking-detail"),
    path("patients/", doctor_patients, name="doctor-patients"),
    path("patient_plan/<int:pk>/", get_patient_plan),
    path("create/patient_plan/<int:pk>/", create_patient_plan),
    path(
        "create/patient_medicine/",
        create_patient_medicine,
        name="create_patient_medicine",
    ),
    path(
        "patient_medicine/<int:pk>/", get_patient_medicine, name="get_patient_medicine"
    ),
    path("comment/<int:pk>/", doctor_comment),
    path("comments/<int:pk>/", list_doctor_comments, name="doctor_comments"),
    path("question/<int:pk>/", add_question),
    path("test/<int:pk>/", create_test),
    path("tests/<int:pk>/", list_patient_tests),
    path("tests/questions/<int:pk>/", list_patient_question),
    path("prescription/<int:pk>/", create_prescription),
    path("prescriptions/<int:pk>/", list_prescriptions),
]
