# Generated by Django 5.0.2 on 2024-03-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("laboratory", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laboratory",
            name="image",
            field=models.ImageField(
                blank=True,
                default="lab_icon.avif",
                null=True,
                upload_to="laboratory_pics",
            ),
        ),
    ]
