# Generated by Django 5.0.2 on 2024-03-11 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0002_alter_laboratory_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="laboratory",
            old_name="rating",
            new_name="rate",
        ),
    ]
