# Generated by Django 5.0.2 on 2024-05-03 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0003_rename_rating_laboratory_rate"),
        ("orders", "0002_creditcard"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("D-Dimer", "D-Dimer"),
                            ("CT. Scan", "CT. Scan"),
                            ("Blood Test", "Blood Test"),
                            ("Echo", "Echo"),
                            ("X-ray", "X-ray"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LabBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateTimeField()),
                ("is_cancelled", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "cancel_reason",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_booking",
                        to="laboratory.laboratory",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_lab",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment_card",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="orders.creditcard",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laboratory.service",
                    ),
                ),
            ],
        ),
    ]
