# Generated by Django 5.0.2 on 2024-05-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0004_service_labbooking"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Service",
            new_name="LabService",
        ),
    ]
