# Generated by Django 5.0.2 on 2024-05-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laboratory", "0005_rename_service_labservice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laboratory",
            name="patient",
        ),
    ]
