# Generated by Django 5.0.2 on 2024-03-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0004_alter_cartitems_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="/medicine.png", null=True, upload_to="profile_pics"
            ),
        ),
    ]
