# Generated by Django 5.0.2 on 2024-03-07 22:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0005_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="medicine.png", null=True, upload_to="profile_pics"
            ),
        ),
    ]
