# Generated by Django 5.0.2 on 2024-05-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0006_alter_product_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.OneToOneField(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="is_fav",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="pharmacy",
            name="image",
            field=models.ImageField(
                blank=True,
                default="pharmacy_icon.png",
                null=True,
                upload_to="pharmacy_pics",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True, default="medicine.png", null=True, upload_to="product_pics"
            ),
        ),
    ]
