# Generated by Django 5.0.2 on 2024-03-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pharmacy", "0007_alter_pharmacy_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
