# Generated by Django 5.0.2 on 2024-05-12 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0007_cart_user_product_is_fav_alter_pharmacy_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pharmacy.product",
                    ),
                ),
                ("pill_dosage", models.CharField(max_length=10)),
            ],
            bases=("pharmacy.product",),
        ),
    ]
