# Generated by Django 5.0.2 on 2024-05-12 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0008_medicine"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="subcategory",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="medicine",
            name="category",
            field=models.CharField(
                choices=[
                    ("Medications", "Medications"),
                    ("Vitamins&supplement", "Vitamins"),
                ],
                default="",
                max_length=40,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="medicine",
            name="subcategory",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Painkillers", "Painkillers"),
                    ("Clot-medications", "Clot-medications"),
                    ("Bronchodilators", "Bronchodilators"),
                    ("Vitamin A", "Vitamin A"),
                    ("Vitamin C", "Vitamin C"),
                    ("Vitamin D", "Vitamin D"),
                ],
                max_length=40,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="Devices",
            fields=[
                (
                    "product_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="pharmacy.product",
                    ),
                ),
                (
                    "category",
                    models.CharField(default="Home Health Care", max_length=50),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Diabetes Care", "Diabetes Care"),
                            ("Blood Pressure Monitor", "Blood Pressure Monitor"),
                            ("Thermometers", "Thermometers"),
                        ],
                        max_length=40,
                        null=True,
                    ),
                ),
            ],
            bases=("pharmacy.product",),
        ),
    ]
