# Generated by Django 5.0.2 on 2024-05-12 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "pharmacy",
            "0009_remove_product_subcategory_remove_product_category_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Devices",
            new_name="Device",
        ),
    ]
