# Generated by Django 5.0.2 on 2024-03-11 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0009_alter_pharmacy_image_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacy",
            name="image",
            field=models.ImageField(
                blank=True,
                default="pharmacy_icon.png",
                null=True,
                upload_to="pharmacy_pics",
            ),
        ),
    ]
