# Generated by Django 5.0.2 on 2024-05-27 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0011_alter_cart_user_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pharmacy",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_pharmacy",
                to="pharmacy.pharmacy",
            ),
            preserve_default=False,
        ),
    ]
