# Generated by Django 5.0.2 on 2024-06-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="connection",
            name="accepted",
        ),
        migrations.RemoveField(
            model_name="connection",
            name="updated",
        ),
    ]
