# Generated by Django 5.0.2 on 2024-02-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
