# Generated by Django 5.0.2 on 2024-02-29 09:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_reset_password_expire_user_reset_password_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="doctorprofile",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANS", "Mansoura"),
                    ("NDAM", "New-Dammitta"),
                    ("CAI", "Cairo"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="government",
            field=models.CharField(
                blank=True,
                choices=[("DAKH", "Dakhlia"), ("DAMI", "Dammitta"), ("CAI", "Cairo")],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="patientprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
