# Generated by Django 5.0.2 on 2024-02-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_doctorprofile_bio_doctorprofile_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorprofile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
