# Generated by Django 5.0.2 on 2024-02-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_doctorprofile_image_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="gender",
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("M", "Male"), ("F", "Female")],
                max_length=1,
                null=True,
            ),
        ),
    ]
