# Generated by Django 5.0.2 on 2024-03-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="city",
        ),
        migrations.RemoveField(
            model_name="patientprofile",
            name="government",
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True,
                choices=[
                    ("MANS", "Mansoura"),
                    ("NDAM", "New-Dammitta"),
                    ("CAI", "Cairo"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="government",
            field=models.CharField(
                blank=True,
                choices=[("DAKH", "Dakhlia"), ("DAMI", "Dammitta"), ("CAI", "Cairo")],
                max_length=100,
                null=True,
            ),
        ),
    ]
