# Generated by Django 5.0.2 on 2024-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_remove_patientprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="user-avatar.png",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
