# Generated by Django 5.0.2 on 2024-03-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0009_alter_doctorprofile_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientprofile",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
