# Generated by Django 5.0.2 on 2024-03-28 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_patientprofile_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="experience",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
