# Generated by Django 5.0.2 on 2024-04-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_doctorprofile_experience"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="experience",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
