# Generated by Django 5.0.2 on 2024-04-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientprofile",
            name="birth_date",
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
