# Generated by Django 5.0.2 on 2024-04-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_remove_patientprofile_birth_date_user_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="doctor_patiens",
            field=models.PositiveBigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
