# Generated by Django 5.0.2 on 2024-05-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_rename_doctor_patiens_doctorprofile_doctor_patients"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorprofile",
            name="doctor_patients",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
