# Generated by Django 5.0.2 on 2024-05-17 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0017_alter_doctorprofile_doctor_patients"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorprofile",
            name="specialization",
            field=models.CharField(
                choices=[
                    ("CARDIOLOGIST", "cardiologist"),
                    ("Neurologist", "Neurologist"),
                    ("Pulmonologist", "Pulmonologist"),
                ],
                default="",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
