# Generated by Django 5.0.2 on 2024-05-20 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("doctor", "0012_patientplan"),
        ("pharmacy", "0011_alter_cart_user_alter_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="PatientMedicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dose", models.PositiveIntegerField()),
                ("program", models.PositiveIntegerField()),
                ("start_date", models.DateField(auto_now_add=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "medicine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patient_medicine",
                        to="pharmacy.medicine",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medicine_plan",
                        to="doctor.patientplan",
                    ),
                ),
            ],
        ),
    ]
