# Generated by Django 5.0.2 on 2024-05-20 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0012_patientplan"),
        ("patient", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmedicine",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicine_plan",
                to="doctor.patientplan",
            ),
        ),
    ]
