# Generated by Django 5.0.2 on 2024-05-20 02:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0012_patientplan"),
        ("patient", "0002_alter_patientmedicine_plan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmedicine",
            name="plan",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medicine_plan",
                to="doctor.patientplan",
            ),
            preserve_default=False,
        ),
    ]
