# Generated by Django 5.0.2 on 2024-05-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0004_patientmedicine_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientmedicine",
            name="quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
