# Generated by Django 5.0.2 on 2024-05-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0005_alter_patientmedicine_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientmedicine",
            name="left",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
