# Generated by Django 5.0.2 on 2024-05-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0006_patientmedicine_left"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patientmedicine",
            name="left",
        ),
    ]
