# Generated by Django 5.0.2 on 2024-05-22 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0007_remove_patientmedicine_left"),
    ]

    operations = [
        migrations.AddField(
            model_name="patientmedicine",
            name="left",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
