# Generated by Django 5.0.2 on 2024-06-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0009_test_question"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
