# Generated by Django 5.0.2 on 2024-06-14 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0018_doctorcomment"),
        ("patient", "0010_alter_question_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="test",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="patient.test",
            ),
        ),
        migrations.AlterField(
            model_name="test",
            name="booking",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_booking",
                to="doctor.doctorbooking",
            ),
        ),
    ]
