# Generated by Django 5.0.2 on 2024-06-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patient", "0011_alter_question_test_alter_test_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="test",
            name="name",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
