# Generated by Django 5.0.2 on 2024-04-01 20:41

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0011_doctorprofile_experience"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service",
                    models.CharField(
                        choices=[
                            ("Messaging", "Messaging"),
                            ("Voice call", "Voice call"),
                            ("In person", "In person"),
                        ],
                        max_length=50,
                    ),
                ),
                ("booking_day", models.DateField()),
                ("booking_hour", models.DateTimeField()),
                ("time_ordered", models.DateTimeField(default=datetime.datetime.now)),
                ("duration", models.CharField(max_length=10)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.doctorprofile",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.patientprofile",
                    ),
                ),
            ],
        ),
    ]
