# Generated by Django 5.0.2 on 2024-04-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorbooking",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="doctorbooking",
            name="service",
        ),
        migrations.RemoveField(
            model_name="doctorbooking",
            name="time_ordered",
        ),
    ]
