# Generated by Django 5.0.2 on 2024-04-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0004_alter_doctorbooking_doctor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctorbooking",
            old_name="booking_hour",
            new_name="booking_date",
        ),
        migrations.RemoveField(
            model_name="doctorbooking",
            name="booking_day",
        ),
    ]
