# Generated by Django 5.0.2 on 2024-04-18 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0006_doctorbooking_cancel_reason_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorbooking",
            name="pending_status",
        ),
    ]
