# Generated by Django 5.0.2 on 2024-04-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0008_alter_doctorbooking_cancel_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorbooking",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
