# Generated by Django 5.0.2 on 2024-05-18 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0009_doctorbooking_is_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorbooking",
            name="review",
            field=models.CharField(default="", max_length=500),
            preserve_default=False,
        ),
    ]
