# Generated by Django 5.0.2 on 2024-05-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0012_patientplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorbooking",
            name="status",
            field=models.CharField(
                choices=[
                    ("upcoming", "Upcoming"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                ],
                default="upcoming",
                max_length=10,
            ),
        ),
    ]
