# Generated by Django 5.0.2 on 2024-05-27 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0013_doctorbooking_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="doctorbooking",
            name="is_cancelled",
        ),
        migrations.RemoveField(
            model_name="doctorbooking",
            name="is_completed",
        ),
    ]
