# Generated by Django 5.0.2 on 2024-05-28 01:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0014_remove_doctorbooking_is_cancelled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="doctorbooking",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
