# Generated by Django 5.0.2 on 2024-05-28 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0016_alter_doctorbooking_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctorbooking",
            name="rating",
            field=models.PositiveIntegerField(
                blank=True,
                default=0,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
