# Generated by Django 5.0.2 on 2024-06-05 12:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("doctor", "0017_alter_doctorbooking_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoctorComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doctor_comment",
                        to="doctor.doctorbooking",
                    ),
                ),
            ],
        ),
    ]
