# Generated by Django 5.0.2 on 2024-05-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_pending_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="pending_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Complete"), ("F", "Failed")],
                default="PAYMENT_STATUS_PENDING",
                max_length=50,
            ),
        ),
    ]
