# Generated by Django 5.0.2 on 2024-05-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_pending_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="creditcard",
            name="expiration_date",
        ),
    ]
