# Generated by Django 5.0.2 on 2024-05-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_creditcard_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="expiration_date",
            field=models.CharField(default="", max_length=5),
            preserve_default=False,
        ),
    ]
