# Generated by Django 5.0.2 on 2024-05-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_creditcard_expiration_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="creditcard",
            options={
                "verbose_name": "Credit Card",
                "verbose_name_plural": "Credit Cards",
            },
        ),
        migrations.AddField(
            model_name="creditcard",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("MC", "MasterCard"),
                    ("VISA", "Visa"),
                    ("AMEX", "American Express"),
                ],
                default="MasterCard",
                max_length=4,
            ),
            preserve_default=False,
        ),
    ]
