# Generated by Django 5.0.2 on 2024-05-28 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_alter_creditcard_options_creditcard_card_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditcard",
            name="card_type",
            field=models.CharField(
                choices=[
                    ("MasterCard", "MasterCard"),
                    ("VISA", "Visa"),
                    ("American Express", "American Express"),
                ],
                max_length=16,
            ),
        ),
    ]
