# Generated by Django 5.0.2 on 2024-06-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_owner_alter_orderitem_order_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditcard",
            name="card_image",
            field=models.ImageField(blank=True, null=True, upload_to="card_images/"),
        ),
    ]
