# Generated by Django 5.0.2 on 2024-06-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_creditcard_card_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="pending_status",
            field=models.CharField(
                choices=[("P", "Pending"), ("C", "Complete"), ("F", "Failed")],
                default="P",
                max_length=50,
            ),
        ),
    ]
